global: 
  resolve_timeout: 5m
  telegram_api_url: "https://api.telegram.org"

templates:
  - '/etc/alertmanager/*.tmpl'

receivers:
  - name: blackhole
  - name: telegram
    telegram_configs:
      - chat_id: -4641918723
        bot_token: 5438507855:AAHgv4PbaGIviUlS4X_mF_uld6ukG_4elgk
        api_url: "https://api.telegram.org"
        parse_mode: HTML
        message: '{{ template "telegram.message" .}}'
        
route:
  group_by: ['ds_id']
  group_wait: 15s
  group_interval: 30s
  repeat_interval: 12h
  receiver: telegram
  routes:
    - receiver: telegram
      matchers:
        - severity="warning,critical"
    - receiver: blackhole
      matchers:
        - alertname="Watchdog"

