version: "3.5"

x-environment:
  &default-back-environment
  # These environment variables will be used by taiga-back and taiga-async.
  # Database settings
  POSTGRES_DB: "taiga"
  POSTGRES_USER: "${POSTGRES_USER}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  POSTGRES_HOST: "taiga-db"
  # Taiga settings
  TAIGA_SECRET_KEY: "${SECRET_KEY}"
  TAIGA_SITES_SCHEME: "${TAIGA_SCHEME}"
  TAIGA_SITES_DOMAIN: "${TAIGA_DOMAIN}"
  TAIGA_SUBPATH: "${SUBPATH}"
  # Email settings.
  EMAIL_BACKEND: "django.core.mail.backends.${EMAIL_BACKEND}.EmailBackend"
  DEFAULT_FROM_EMAIL: "${EMAIL_DEFAULT_FROM}"
  EMAIL_USE_TLS: "${EMAIL_USE_TLS}"
  EMAIL_USE_SSL: "${EMAIL_USE_SSL}"
  EMAIL_HOST: "${EMAIL_HOST}"
  EMAIL_PORT: "${EMAIL_PORT}"
  EMAIL_HOST_USER: "${EMAIL_HOST_USER}"
  EMAIL_HOST_PASSWORD: "${EMAIL_HOST_PASSWORD}"
  # Rabbitmq settings
  RABBITMQ_USER: "${RABBITMQ_USER}"
  RABBITMQ_PASS: "${RABBITMQ_PASS}"
  # Telemetry settings
  ENABLE_TELEMETRY: "${ENABLE_TELEMETRY}"
  # ...your customizations go here

x-volumes:
  &default-back-volumes
  # These volumens will be used by taiga-back and taiga-async.
  - taiga-static-data:/taiga-back/static
  - taiga-media-data:/taiga-back/media
  # - ./config.py:/taiga-back/settings/config.py

services:
  taiga-db:
    image: postgres:12.3
    container_name: taiga-db
    user: root
    environment:
      POSTGRES_DB: "taiga"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    command: ["postgres", "-c", "logging_collector=on", "-c", "log_directory=/var/log/postgresql", "-c", "log_filename=postgresql.log", "-c", "log_statement=all"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 2s
      timeout: 15s
      retries: 5
      start_period: 3s
    volumes:
      - taiga-db-data:/var/lib/postgresql/data:z
      - ./logs/postgres:/var/log/postgresql:z
    networks:
      - taiga
    logging:
      driver: fluentd
      options:
        fluentd-address: tcp://localhost:6000
        tag: taiga-db
    depends_on:
      vector:
        condition: service_healthy

  taiga-back:
    image: taigaio/taiga-back:latest
    container_name: taiga-back
    environment: *default-back-environment
    volumes: *default-back-volumes
    networks:
      - taiga
    depends_on:
      taiga-db:
        condition: service_healthy
      taiga-events-rabbitmq:
        condition: service_started
      taiga-async-rabbitmq:
        condition: service_started
      vector:
        condition: service_healthy

    logging:
      driver: fluentd
      options:
        fluentd-address: tcp://localhost:6000
        tag: taiga-back

  taiga-async:
    image: taigaio/taiga-back:latest
    container_name: taiga-async
    entrypoint: ["/taiga-back/docker/async_entrypoint.sh"]
    environment: *default-back-environment
    volumes: *default-back-volumes
    networks:
      - taiga
    depends_on:
      taiga-db:
        condition: service_healthy
      taiga-events-rabbitmq:
        condition: service_started
      taiga-async-rabbitmq:
        condition: service_started
      vector:
        condition: service_healthy
    logging:
      driver: fluentd
      options:
        fluentd-address: tcp://localhost:6000
        tag: taiga-async

  taiga-async-rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: taiga-async-rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: "${RABBITMQ_ERLANG_COOKIE}"
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASS}"
      RABBITMQ_DEFAULT_VHOST: "${RABBITMQ_VHOST}"
    hostname: "taiga-async-rabbitmq"
    volumes:
      - taiga-async-rabbitmq-data:/var/lib/rabbitmq
      - ./logs/async-rabbitmq:/var/log/rabbitmq
    networks:
      - taiga
    logging:
      driver: fluentd
      options:
        fluentd-address: tcp://localhost:6000
        tag: taiga-async-rabbitmq
    depends_on:
      vector:
        condition: service_healthy

  taiga-front:
    image: taigaio/taiga-front:latest
    container_name: taiga-front
    environment:
      TAIGA_URL: "${TAIGA_SCHEME}://${TAIGA_DOMAIN}"
      TAIGA_WEBSOCKETS_URL: "${WEBSOCKETS_SCHEME}://${TAIGA_DOMAIN}"
      TAIGA_SUBPATH: "${SUBPATH}"
      # ...your customizations go here
    networks:
      - taiga
    logging:
      driver: fluentd
      options:
        fluentd-address: tcp://localhost:6000
        tag: taiga-front
    depends_on:
      vector:
        condition: service_healthy
    # volumes:
    #   - ./conf.json:/usr/share/nginx/html/conf.json

  taiga-events:
    image: taigaio/taiga-events:latest
    container_name: taiga-events
    environment:
      RABBITMQ_USER: "${RABBITMQ_USER}"
      RABBITMQ_PASS: "${RABBITMQ_PASS}"
      TAIGA_SECRET_KEY: "${SECRET_KEY}"
    networks:
      - taiga
    depends_on:
      taiga-events-rabbitmq:
        condition: service_started
      vector:
        condition: service_healthy
    logging:
      driver: fluentd
      options:
        fluentd-address: tcp://localhost:6000
        tag: taiga-events

  taiga-events-rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: taiga-events-rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: "${RABBITMQ_ERLANG_COOKIE}"
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASS}"
      RABBITMQ_DEFAULT_VHOST: "${RABBITMQ_VHOST}"
    hostname: "taiga-events-rabbitmq"
    volumes:
      - taiga-events-rabbitmq-data:/var/lib/rabbitmq
      - ./logs/events-rabbitmq:/var/log/rabbitmq
    networks:
      - taiga
    logging:
      driver: fluentd
      options:
        fluentd-address: tcp://localhost:6000
        tag: taiga-events-rabbitmq
    depends_on:
      vector:
        condition: service_healthy

  taiga-protected:
    image: taigaio/taiga-protected:latest
    container_name: taiga-protected
    environment:
      MAX_AGE: "${ATTACHMENTS_MAX_AGE}"
      SECRET_KEY: "${SECRET_KEY}"
    networks:
      - taiga
    logging:
      driver: fluentd
      options:
        fluentd-address: tcp://localhost:6000
        tag: taiga-protected
    depends_on:
      vector:
        condition: service_healthy

  taiga-gateway:
    image: nginx:1.19-alpine
    container_name: taiga-gateway
    ports:
      - "9000:80"
    volumes:
      - ./taiga-gateway/taiga.conf:/etc/nginx/conf.d/default.conf
      - taiga-static-data:/taiga/static
      - taiga-media-data:/taiga/media
      - ./logs/nginx:/var/log/nginx
    networks:
      - taiga
    depends_on:
      taiga-front:
        condition: service_started
      taiga-back:
        condition: service_started
      taiga-events:
        condition: service_started
      vector:
        condition: service_healthy
    logging:
      driver: fluentd
      options:
        fluentd-address: tcp://localhost:6000
        tag: taiga-gateway
    

  ### Далее идут моменты, связанные с конфигурацией observability
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
      - promtetheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.console.templates=/etc/prometheus/consoles
      - --storage.tsdb.retention.time=200h
      - --web.enable-lifecycle
    ports:
      - "9090:9090" 
    restart: always
    networks:
      - taiga
    logging:
      driver: fluentd
      options:
        fluentd-address: tcp://localhost:6000
        tag: prometheus
    depends_on:
      vector:
        condition: service_healthy
    

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    networks:
      - taiga
    depends_on:
      prometheus:
        condition: service_started
      vector:
        condition: service_healthy
    logging:
      driver: fluentd
      options:
        fluentd-address: tcp://localhost:6000
        tag: taiga-gateway

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox-exporter
    volumes:
      - ./blackbox/blackbox.yml:/config/blackbox.yml
    command:
      - --config.file=/config/blackbox.yml
    restart: always
    networks:
      - taiga
    ports:
      - "9115:9115"
    depends_on:
      prometheus:
        condition: service_started
      vector:
        condition: service_healthy
    logging:
      driver: fluentd
      options:
        fluentd-address: tcp://localhost:6000
        tag: blackbox-exporter

  postgres-exporter:
    image: bitnami/postgres-exporter:0.15.0
    container_name: postgres-exporter
    environment:
      - DATA_SOURCE_NAME=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@taiga-db:5432/taiga?sslmode=disable
    restart: always
    networks:
      - taiga
    depends_on:
      prometheus:
        condition: service_started
      vector:
        condition: service_healthy
    logging:
      driver: fluentd
      options:
        fluentd-address: tcp://localhost:6000
        tag: postgres-exporter
    
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:1.0
    container_name: prometheus-exporter
    restart: always
    command:
      - -nginx.scrape-uri=http://taiga-gateway:80/stub_status
    networks:
      - taiga
    depends_on:
      prometheus:
        condition: service_started
      vector:
        condition: service_healthy
    logging:
      driver: fluentd
      options:
        fluentd-address: tcp://localhost:6000
        tag: nginx-exporter

  taiga-async-rabbitmq-exporter:
    image: kbudde/rabbitmq-exporter:latest
    container_name: taiga-async-rabbitmq-exporter
    hostname: taiga-async-rabbitmq-exporter
    environment:
      - RABBIT_URL=http://taiga-async-rabbitmq:15672
      - RABBIT_USER=${RABBITMQ_USER}
      - RABBIT_PASSWORD=${RABBITMQ_PASS}
    restart: always
    networks:
      - taiga
    depends_on:
      prometheus:
        condition: service_started
      vector:
        condition: service_healthy
    logging:
      driver: fluentd
      options:
        fluentd-address: tcp://localhost:6000
        tag: taiga-async-rabbitmq-exporter

  taiga-events-rabbitmq-exporter:
    image: kbudde/rabbitmq-exporter:latest
    container_name: taiga-events-rabbitmq-exporter
    hostname: taiga-events-rabbitmq-exporter
    environment:
      - RABBIT_URL=http://taiga-events-rabbitmq:15672
      - RABBIT_USER=${RABBITMQ_USER}
      - RABBIT_PASSWORD=${RABBITMQ_PASS}
    restart: always
    networks:
      - taiga
    depends_on:
      prometheus:
        condition: service_started
      vector:
        condition: service_healthy
    logging:
      driver: fluentd
      options:
        fluentd-address: tcp://localhost:6000
        tag: taiga-events-rabbitmq-exporter

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GS_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - taiga
    restart: always 
    logging:
      driver: fluentd
      options:
        fluentd-address: tcp://localhost:6000
        tag: taiga-events-rabbitmq-exporter
    depends_on:
      vector:
        condition: service_healthy

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - ./alertmanager/template.tmpl:/etc/alertmanager/template.tmpl
      - alertmanager_data:/alertmanager
    ports:
      - "9093:9093"  # Alertmanager web UI
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
    restart: always
    networks:
      - taiga
    logging:
      driver: fluentd
      options:
        fluentd-address: tcp://localhost:6000
        tag: alertmanager
    depends_on:
      vector:
        condition: service_healthy

  elasticsearch:
    container_name: elasticsearch
    build:
      context: elasticsearch/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,Z
      - elasticsearch-2:/usr/share/elasticsearch/data:Z
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      node.name: elasticsearch
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      discovery.type: single-node
    restart: unless-stopped
    networks:
      - taiga
    healthcheck:
      test: curl -s http://elasticsearch:9200 >/dev/null || exit 1
      interval: 15s
      timeout: 10s
      retries: 50

  kibana:
    container_name: kibana
    build:
      context: kibana/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
    ports:
      - 5601:5601
    environment:
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
    depends_on:
      elasticsearch:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - taiga

  vector:
    image: timberio/vector:latest
    build:
      context: vector/
    container_name: vector
    volumes:
      - ./vector/config/vector.toml:/etc/vector/vector.toml
      - ./logs:/var/log/apps
    command: --config /etc/vector/vector.toml
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
    ports:
      - 8686:8686
      - 6000:6000
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "6000"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - taiga

  es_setup:
    container_name: es_setup
    profiles:
      - setup
    build:
      context: setup/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    init: true
    volumes:
      - ./setup/entrypoint.sh:/entrypoint.sh:ro,Z
      - ./setup/lib.sh:/lib.sh:ro,Z
      - ./setup/roles:/roles:ro,Z
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
      BEATS_SYSTEM_PASSWORD: ${BEATS_SYSTEM_PASSWORD:-}
    depends_on:
      - elasticsearch
    networks:
      - taiga

volumes:
  taiga-static-data:
  taiga-media-data:
  taiga-db-data:
  taiga-async-rabbitmq-data:
  taiga-events-rabbitmq-data:

  promtetheus_data:
  grafana_data:
  alertmanager_data:
  elasticsearch-2:
  
networks:
  taiga:
